// export const BASE_URL = "https://api.impsguru.com/";
// export const BASE_URL = "https://uat.impsguru.com/";
// export const BASE_URL = "https://api.dillipay.com/";
// export const BASE_URL = "http://192.168.1.14/impsguru-php/";
export const BASE_URL = "https://newapi.impsguru.com/";

const ApiEndpoints = {
  COOKIE: "sanctum/csrf-cookie",

  REQUEST_HASH: "auth/signRequest",
  GET_LOGIN_HISTORY: "user/getLoginHistory",

  GET_FILES: "user/getFile",
  GET_SCHEME: "schemes/getScheme",
  EDIT_SUPER_RATE: "admin/updateSuperRate",
  GET_UTILITY_SCHEME: "schemes/utilitySchemes",
  GET_DMT_SCHEMA: "schemes/dmtSchemes",
  GET_PAYOUT_SCHEMA: "schemes/payoutSchemes",
  GET_PAYOUT2_SCHEMA: "schemes/payout2Schemes",
  AGEMENT_DATE: "admin/aggreementDate",
  SEND_OTP_Okyc: "user/sendOtpOkyc",
  VERIFY_OTP_OKYC: "user/verifyOtpOkyc",
  UPDATE_UTILITY_SCHEME: "schemes/updateUtilityScheme",
  UPDATE_PAYOUT_SCHEME: "schemes/updatePayoutScheme",
  UPDATE_PAYOUT2_SCHEME: "schemes/updatePayout2Scheme",
  UPDATE_DMT_SCHEME: "schemes/updateDmtScheme",
  CREATE_UTILITY_SCHEME: "schemes/createUtilityScheme",
  CREATE_PAYOUT_SCHEME: "schemes/createPayoutScheme",
  CREATE_PAYOUT2_SCHEME: "schemes/createPayout2Scheme",
  CREATE_DMT_SCHEME: "schemes/createDmtScheme",
  GET_NEWS: "admin/news",

  GET_ME_USER: "user/getUser",

  OBTAIN_DOCS: "auth/getDocs",
  GET_RECENT_DATA: "reports/recentHistory",
  GET_USERS: "user/getUsers",
  GET_USERS_ACC: "",
  VERIFY_PIC: "admin/approveRejectKyc",
  PAYOUT_BENES: "admin/payoutBene",
  PAYOUT_BENE_KYC_DOCS: "admin/beneKycDoc",
  GET_USER_BY_USERNAME: "auth/getUserByUsername",
  GET_USER_BY_ID: "admin/getUserById",
  // RESEND_OTP: "wallet/resendOtp",
  USER_PROFIT: "admin/userProfitability",
  DELETE_USER: "admin/deleteUser",
  API_USERS_CHARGES: "admin/charges",
  ADMIN_PRABHU_CHARGES: "admin/psrabhuCharge",
  API_USERS_KEYS: "admin/userKeys",
  BLOCK_UNBLOCK: "admin/blockUnblock",
  GET_TRANSACTIONS: "admin/getTransactions",
  GET_ACC_TRANSACTIONS: "",
  // GET_TRANSACTIONS: "admin/getTransactions",
  CRED_REQ: "admin/getCrRequests",
  CRED_REQ_APPROVE: "admin/crActions",
  GET_OPERATOR: "admin/getOperators",
  ACTIVE_INACTIVE_OPERATOR: "admin/changeOperatorStatus",
  UPDATE_OPERATOR: "admin/updateOperator",
  ADD_OPERATOR: "admin/createOperator",
  ADD_BANK: "admin/createBank",
  CHANGE_ROUTE_OPERATOR: "admin/changeRoute",
  CHANGE_OPERATOR_PIPE: "admin/changePipe",
  GET_ROUTE: "admin/getRoutes",
  GET_CATEGORIES: "admin/getCategories",
  BBPS_GET_CATEGORIES: "bbps/getCategories",
  BBPS_GET_BILLERS: "bbps/getBillers",
  BBPS_GET_BILLERS_DETAILS: "bbps/getBillerDetails",
  BBPS_FETCH_BILL: "bbps/fetchBill",

  // ****************************** NEW API'S ******************************
  SIGN_IN: "auth/signIn",
  LOGIN_OTP_VALIDATE: "auth/secureLogin",
  LOGOUT: "auth/Logout",
  FORGOT_PASS: "auth/forgetPassword",
  RESET_MPIN: "auth/resetMpin",
  RESEND_OTP: "auth/resendOtp",
  CHANGE_PASS: "auth/changePassword",
  CHANGE_MPIN: "auth/changeMpin",
  INITIATE_NUMBER: "auth/initiateChangeNumber",
  VERIFY_CHAGNE_NUMBER: "auth/verifyChangeNumber",

  GET_ACCOUNTS: "account/getAccounts",
  CREATE_ACCOUNT: "account/createAccount",
  DELETE_ACCOUNT: "account/deleteAccount",
  UPDATE_ACCOUNT: "account/updateAccount",
  GET_SERVICES: "service/getServices",
  CREATE_SERVICE: "service/createService",
  UPDATE_SERVICE: "service/updateService",
  GET_TEMPLATES: "template/getTemplates",
  CREATE_TEMPLATE: "template/createTemplate",
  UPDATE_TEMPLATE: "template/updateTemplate",
  DELETE_TEMPLATE: "template/deleteTemplate",
  GET_LOGS: "auditlog/getAuditLogs",
  DELETE_LOG: "auditlog/deleteAuditLog",
  GET_LOG: "auditlog/getAuditLog",
  GET_WALLETLEDGER: "walletledger/getWalletLedgers",

  // ****************************** NEW API'S ABOVE ******************************

  GET_FUND_REQUESTS: "fundrequest/getFundRequests",
  CREATE_FUND_REQUEST: "fundrequest/createFundRequest",
  UPDATE_FUND_REQUEST: "fundrequest/updateFundRequest",
  DELETE_FUND_REQUEST: "fundrequest/deleteFundRequest",
  GET_BANKS: "bank/getBanks",
  // ****************************** NEW API'S ABOVE ******************************
  GET_COMMISSION_RULE: "commission/getCommissions",
  GET_NOTIFICATION: "notification/getNotification",
  MARK_READ_NOTI: "notification/updateNotification",
  ADMIN_NOTIFICATION: "notification/createNotification",
  UPDATE_NOTIFICATION: "notification/updateNotification",
  DELETE_NOTIFICATION: "notification/deleteNotification",

  GET_BANK_STATEMENTS: "bankStatement/getBankStatement",
  CREATE_BANK_STATEMENT: "bankStatement/createBankStatement",
  UPDATE_BANK_STATEMENT: "bankStatement/updateBankStatement",
  DELETE_BANK_STATEMENT: "bankStatement/deleteBankStatement",
  GET_BANK_STATEMENT_SCHEMA: "bankStatement/getBankStatementSchema",

  GET_ACCOUNT_STATEMENTS: "accountStatement/getAccountStatement",
  CREATE_ACCOUNT_STATEMENT: "accountStatement/createAccountStatement",
  UPDATE_ACCOUNT_STATEMENT: "accountStatement/updateAccountStatement",
  DELETE_ACCOUNT_STATEMENT: "accountStatement/deleteAccountStatement",
  GET_ACCOUNT_STATEMENT_SCHEMA: "accountStatement/getAccountStatementSchema",

  CREATE_BANK: "bank/createBank",
  UPDATE_BANK: "bank/updateBank",
  DELETE_BANK: "bank/deleteBank",

  GET_DMT_TXN: "dmt/getDmtTxns",
  GET_BBPS_TXN: "bbps/getBbpsTxns",
  GET_AEPS_TXN: "aeps/getAepsTxns",
  GET_MATM_TXN: "matm/getMatmTxns",
  GET_PAYOUT_TXN: "payout/getPayoutTxns",
  GET_RECHARGE_TXN: "recharge/getRechargeTxns",
  GET_IRCTC_TXN: "irctc/getIrctcTxns",
  GET_FUNDREQUEST_SCHEMA: "fundrequest/getFundRequestsSchema",
  GET_ACCOUNT_SCHEMA: "account/getAccountSchema",
  GET_BANK_SCHEMA: "bank/getBankSchema",
  GET_NOTIFICATION_SCHEMA: "notification/getNotificationSchema",
  GET_COLOR_SCHEMA: "layout/colorSchema",
  GET_COLOURS: "layout/getColours",
  CREATE_COLOUR: "layout/createColour",
  UPDATE_COLOUR: "layout/updateColour",
  CREATE_COMMISSION_RULE: "commission/createCommissionRule",
  GET_COMMISSION_SCHEMA: "commission/getCommissionSchema",
  UPDATE_COMMISSION_RULE: "commission/updateCommissionRule",
  GET_SENDER: "payout/getSender",
  REGISTER_SENDER: "payout/registerSender",
  REGISTER_SENDER_SCHEMA: "payout/registerSenderSchema",
  VERIFY_SENDER_SCHEMA: "payout/verifySenderSchema",
  VERIFY_SENDER: "payout/verifySender",
  PAYOUT_OTP: "payout/otpExp",
  ADD_BENEFICIARY_SCHEMA: "payout/getBeneficiarySchema",
  CREATE_BENEFICIARY: "payout/createBeneficiary",
  DELETE_BENEFICIARY: "payout/deleteBeneficiary",
  PAYOUT: "payments/v2/userPayOut",
  PAYOUT_SCHEMA: "payments/v2/getPayoutSchema",
  UPDATE_USER_PERMISSIONS: "user/updateUserPermissions",
  GET_PLANS_BY_OPERATOR: "recharge/getPlansByOperator",
  RECHARGE: "recharge/recharge",
  GET_SIDENAV: "layout/getSideNav",
  GET_ACCOUNT_STATEMENT: "accountStatement/getStatements",
  GET_PLANS: "plan/getPlans",
  CREATE_PLAN: "plan/createPlan",
  UPDATE_PLAN: "plan/updatePlan",
  GET_PLAN_SCHEMA: "plan/getPlanSchema",
  GET_UPI_SCHEMA: "payout/getBeneficiarySchemaUpi",
  UPDATE_USER_STATUS: "user/blockAndUnblock",

  CHANGE_USER_LAYOUT: "user/changeLayout",

  DMT1: "dmt1/remitterStatus",
  REGISTER_DMT1_BENEFICIARY: "dmt1/registerBeneficiary",
  ADD_DMT1_SCHEMA: "dmt1/registerBeneficiary",

  CREATE_USER: "signup/createUser",
  GET_SIGNUP_SCHEMA: "signup/getSignupSchema",
  DMT1: "dmt1/remitterStatus",
  DMT1_REGISTER: "dmt1/registerRemitter",

  CREATE_BASIC: "business/createBasic",
  CREATE_CONTACT: "business/createContact",
  CREATE_ADDRESS: "business/createAddress",
  CREATE_IDENTIFICATION: "business/createIdentification",
  CREATE_BANK: "business/createBank",
  CREATE_DOCUMENTS: "business/createDocuments",
  CREATE_KYC: "business/createKyc",
  CREATE_STATUS: "business/createStatus",

  BASIC_SCHEMA: "business/basicSchema",
  CONTACT_SCHEMA: "business/contactSchema",
  ADDRESS_SCHEMA: "business/addressSchema",
  IDENTIFICATION_SCHEMA: "business/identificationSchema",
  BANK_SCHEMA: "business/bankSchema",
  DOCUMENTS_SCHEMA: "business/documentsSchema",
  KYC_SCHEMA: "business/kycSchema",
  STATUS_SCHEMA: "business/statusSchema",

  WALLET_LIST: "wallet/getW2WTransactions",
  WALLET_GET_RECEIVER: "wallet/getReceiver",
  WALLET_GET_W2W_TRANSACTION: "wallet/getW2WTransaction",
  WALLET_CREATE: "wallet/createW2W",
  // WALLET_UPDATE: "wallet/update",
  // WALLET_DELETE: "wallet/delete",

  // ****************************** NEW API'S ABOVE ******************************

  GET_ACC_BANKS: "",
  UPDATE_BANKS: "admin/changeBankStatus",
  ADD_ACCOUNT: "admin/createNewAcc",
  ADD_ACCOUNT_TXN: "admin/addAccTxn",
  DELETE_TXN: "admin/deleteTxn",
  GET_MASSEGE: "admin/getMessages",
  GET_OUT_MASSEGE: "admin/getOutMessages",
  GET_WEBHOOK: "admin/getWebHooks",
  // GET_ACCOUNT_STATEMENT: "admin/getAccStatement",
  GET_BANK_STATEMENT: "admin/getBankStatement",
  ADD_BANK_TXN: "admin/addBankTxn",
  DELETE_BANK_TXN: "admin/deleteBankTxn",
  GET_PENDING_ACCOUNT_TRANSACTION: "admin/getPendingBankTxn",
  GET_STATUS: "admin/checkTxnStatus",
  CHANGE_STATUS: "admin/changeTxnStatus",

  BLOCK_UNBLOCK_PLANS: "",
  ADD_PLAN: "admin/createPlan",
  DELETE_PLAN: "admin/deletePlan",
  COMPLAINTS: "admin/getIssues",
  GET_USER_AD_ASM: "admin/getUserAdAsm",

  ADMIN_OP_SERVICE: "admin/service",
  VERIFY_PAN: "admin/verifyPan",
  ADMIN_PG_ORDERS: "admin/pgOrders",
  VERIFY_AADHAAR: "admin/verifyAadhaar",
  TWOFA_AUTH: "auth/twoFactorAuthentication",
  WALLET_DEBIT: "/admin/walletDebit",
  CREATE_VA: "admin/createVa",
  VIRTUAL_ACCS: "admin/virtualAccounts",
  VIRTUAL_TRANSACTIONS: "admin/vaTransactions",
  BANK_DETAILS: "admin/bankDepData",
  SEND_OTP: "user/sendOtp",
  GET_API_TOKEN: "user/getApiToken",
  GET_API_KEY: "user/getApiKey",
  RESET_API_TOKEN: "user/resetApiToken",
  RESET_API_KEY: "user/resetApiKey",

  // wallet
  GET_BANK_CREDIT_REQ: "wallet/getBanksForCrRequest",
  CREDIT_REQ: "wallet/createCrRequest",
  MONEY_TRANSFER: "wallet/w1ToW1Transfer",
  DMT_RATE_CHANGE: "wallet/editRetByAd",
  W2TOW1_TRANSFER: "wallet/w2ToW1Transfer",
  GET_NUMBER_INFO: "prepaid/getNumberInfo",
  PREPAID_RECHARGE: "prepaid/prepaidRecharge",
  // dmr
  DMR_SETTLEMENTS: "/dmr/settlementBene",
  CHANGE_NAME_OTP: "dmr/updateRemitter",
  CHANGE_NAME: "dmr/validateRemitter",
  GET_REMMITTER_STATUS: "dmr/getRemitterStatus", // fast response
  NEW_GET_REMMITTER_STATUS: "dmr/remitterStatusExpress",
  DMT2_REM_STAT: "dmr/getRemitterStatusDmt2",
  REF_REMMITTER_STATUS: "dmr/refreshRemitterStatus", //late response
  REMOVE_BENE: "dmr/removeBeneficiary",
  DMT2_REM_BENE: "dmr/removeBeneficiaryDmt2",
  BENE_KYC: "dmr/beneKyc",
  VALIDATE_OTP: "dmr/validateRemitter",
  VALIDATE_DMT2: "dmr/validateRemitterDmt2",

  NEW_VALIDATE_OTP: "dmr/verifyExpRemitter",
  VERIFY_REM_UPI: "dmr/verifyRemitterUpi",
  EKYC_INITIATE: "dmr/initiateEkyc",
  GET_REMMITTER_STATUS_ACC: "dmr/getRemitterStatusByAcc",
  GET_BANK_DMR: "dmr/getBanks",
  // DMT2_BANK_LIST: "dmr/getBanksDmt2",
  DMT2_BANK_LIST: "dmr/getLiveBanksDmt2",
  ADD_BENE: "dmr/registerBeneficiary",
  DMT2_ADD_BENE: "dmr/registerBeneficiaryDmt2",
  ADD_REM: "dmr/registerRemitter",
  NEW_ADD_REM: "dmr/registerExpRemitter",
  GET_BLOCKED_AC: "admin/blockedAccounts",

  DMT2_ADD_REM: "dmr/registerRemitterDmt2",
  ADD_BENE_EXPRESS: "dmr/addBenExpress",
  ADD_BENE_SUPER: "dmr/addBenExpress",
  REMOVE_BENE_EXPRESS: "dmr/delBenExpress",

  ADD_REM_EXPRESS: "dmr/registerExpRemitter",
  ADD_REM_SUPER: "dmr/registerSupRemitter",
  GET_REMITTER_STATUS_UPI: "dmr/remitterStatusUpi",
  REMOVE_BENE_UPI: "dmr/deleteBenUpi",
  ADD_REM_UPI: "dmr/registerRemitterUpi",
  ADD_BENE_UPI: "dmr/addBenUpi",
  EXP_TRANSFER: "dmr/expressTxn",
  SUPER_TRANSFER: "dmr/superTransfer",
  DMR_MONEY_TRANSFER: "dmr/transactionDmr",
  VERIFY_ACC: "dmr/accountVerification",
  DMT2_MT: "dmr/transactionDmt2",

  BBPS_CATEGORIES: "prepaid/getCategories",
  // BBPS_GET_BILLERS: "prepaid/getBillers",
  // BBPS_GET_BILLERS_DETAILS: "prepaid/getBillerDetails",
  // BBPS_FETCH_BILL: "prepaid/fetchBillInst",
  // BBPS_PAY_BILL: "prepaid/payBillInst",

  //recharges and bill payment
  RECH_FETCH_BILL: "prepaid/fetchBill",
  RECH_PAY_BILL: "prepaid/payBill",

  // user
  GET_ROLL: "",
  RAISE_ISSUE_USER: "user/raiseIssue",
  UPLOAD_USER_PHOTO: "user/uploadProfileImg",
  UPLOAD_USER_KYC: "user/uploadKycImg",
  UPDATE_USER_PROFILE: "user/updateProfile",
  ADD_SETTLEMENT_ACC: "/user/addSettlementAcc",
  GET_SETTLEMENT_ACCS: "/user/getSettlementAcc",
  GET_VIRTUAL_ACC: "user/getVa",
  //
  HANDLE_ISSUE: "admin/updateIssue",
  BANK_SETTELMENT: "dmr/accSettlementNew", ///
  VERIFY_ACC_UPI: "dmr/vpaVerification",
  UPI_PAY: "dmr/upiPay",

  BILLPAY_CC: "dmr/billPaymentCc",
  OLD_TRANSACTIONS: "admin/getOldTransactions",

  // aeps
  AEPS_BANK: "aeps/getBanks",
  AEPS_CASHWITHDRAWAL: "aeps/cashWithdrawl",
  AEPS_APAY: "aeps/aadhaarPay",
  AEPS_BALANCE: "aeps/balanceInquiry",
  AEPS_STATEMENT: "aeps/miniStatement",
  AEPS_INITIATE: "aeps/initiateSignup",
  AEPS_VALIDATE: "aeps/validateSignup",
  AEPS_OUTLET_STATUS: "aeps/outletLoginStatus",
  AEPS_OUTLET_LOGIN: "aeps/outletLogin",

  DMR_WALLET_TRANSFER: "dmr/walletTransfer",

  CHANGE_USERNAME_OTP: "",
  CHANGE_USERNAME: "",
  GET_BOOKS: "books/getBooks",
  ADD_BOOKS: "books/addBook",
  KHATA_BOOKS_STATEMENT: "books/getBookTransaction",
  ADD_BOOKS_STATEMENT: "books/addBookTransaction",

  // REG user
  USER_REG: "wallet/userRegistration",
  USER_PERSONALINFO: "wallet/addPersonalInfo",
  USER_BUSINESSINFO: "wallet/addBusinessInfo",
  GET_DISTRICTS: "prepaid/getDistricts",
  GET_STATES: "getStates",
  GET_HANDLER_DETAILS: "auth/getUserByUsername",
  VERIFY_MOBILE: "auth/verifyMobile",
  SIGN_UP_LAST: "aeps/initiateSignup",
  GET_USERROLES: "onboarding/userOnboarding",

  // Admin employees
  EMPLOYEES: "/emp/getEmployee",
  ADD_EMPLOYEES: "emp/createEmp",
  EDIT_EMPLOYEES: "emp/updateEmp",
  //Admin Dashboard
  ADMIN_DASHBOARD_GET_BANK_BALANCE: "reports/getBankBalance",
  ADMIN_DASHBOARD_GET_API_BALANCE: "admin/apiBalances",
  ADMIN_DASHBOARD_GET_WALLET_BALANCE: "reports/getFloat",
  ADMIN_DASHBOARD_GET_PRIMARY_BALANCE: "reports/getPrimaryData",
  ADMIN_DASHBOARD_GET_TERTIARY_BALANCE: "reports/getTertiaryData",
  ADMIN_DASHBOARD_GET_GRAPH_DATA: "reports/getGraphData",
  ADMIN_DASHBOARD_GET_TXN_DATA: "reports/transactionCount",
  ADMIN_DASHBOARD_GET_USER_DATA: "admin/getUserCount",
  ASM_PRODUCTION_SALE_DATA: "reports/asmReportAll",
  GET_RET_PROD_SALE: "reports/getTertiaryDataServiceWise",

  ACCOUNT_BALANCE: "admin/accBalance",
  DASHBOARD_ASM_REPORT: "reports/getTertiaryDataServiceWise",
  MY_EARNINGS: "reports/myEarnings",
  GET_TRIPLE_BARCHART_DATA: "reports/getTertiaryDataServiceWise",
  GET_ASM_TRIPLE_BARCHART_DATA: "reports/asmReportAll",
  //admin acc
  ADMIN_ACC_GET_USER: "reports/getUsersForAcc",
  ADMIN_ACC_GET_TXN: "reports/getTransactionsForAcc",
  ADMIN_ACC_GET_LEADGER: "reports/getLedgerForAcc",
  ADMIN_ACC_GET_BANK_TXN: "reports/getBanktransactionForAcc",
  ADMIN_ACC_GET_ACC_USER: "reports/getAccUsersForAcc",
  ACC_GET_ACC_USER: "reports/getUsersForAcc",
  GET_COUNT: "admin/getCount",
  ADMIN_ACCOUNTS_LIMITS: "admin/accountLimit",
  // nepal
  PRABHU_KYC: "nepalTransfer/initiateEKycPrabhu",
  MACHINE_KYC: "nepalTransfer/eKycenrollment",
  NEPAL_CUSTOMER_STATUS: "nepalTransfer/getCustomerByMobileOrId",
  NEPAL_OTP: "nepalTransfer/sendOtp",
  NEPAL_STATE_DIS: "nepalTransfer/getStateDistrict",
  NEPAL_STATIC_DATA: "nepalTransfer/getStaticData",
  NEPAL_CREATE_CUSTOMER: "nepalTransfer/createCustomer",
  NEPAL_CREATE_RECEIVER: "nepalTransfer/CreateReceiver",
  NEPAL_BANK_BRANCH: "nepalTransfer/AcPayBankBranchList",
  NEPAL_VALIDATE_RECEIVER: "nepalTransfer/ValidateBankAccount",
  NEPAL_CUSTOMER_ONBOARD: "nepalTransfer/customerOnboarding",
  NEPAL_SEND_TRANSACTION: "nepalTransfer/sendTransaction",
  NEPAL_TRANSACTION: "nepalTransfer/SearchTransaction",
  NEPAL_UVTRANSACTION: "nepalTransfer/UnverifiedTransactions",
  NEPAL_UVCUSTOMERS: "nepalTransfer/UnverifiedCustomers",
  NEPAL_COMPLIANCE_TRANSACTION: "nepalTransfer/ComplianceTransactions",
  GET_SERVICE_CHARGE: "nepalTransfer/GetServiceChargeByCollection",

  ADMIN_SERVICES: "admin/updateServices",
  USER_SERVICES: "admin/getUserServices",
  GET_SIGNUP_ROLES: "onboarding/userOnboarding",

  // flight
  GETAIRPORTS: "flights/getAirports",
  GET_CALENDAR_FARE: "flights/GetCalendarFareByMonth",
  SEARCH_FLIGHTS: "flights/searchFlight",
  PRICE_CHECK_FLIGHTS: "flights/priceCheck",
  BOOK_FLIGHT: "flights/flightBooking",
  CREATE_ORDER_CMS: "user/createOrderCms",
  // pg api
  CREATE_ORDER: "user/createOrderPg",
  // IRCTC AUTH
  IRCTC_AUTH_PAYMENT: "prod/irctc/authPayment",
  UAT_IRCTC_AUTH_PAYMENT: "uat/irctc/authPayment",
  // aeps2 api
  AEPS2_OUTLETREG: "aeps/merchantOnboardingFp",
  AEPS2_MERCHANTEKYC: "aeps/merchantEkycFp",
  AEPS2_VALIDATEOTP: "aeps/validateOtpFp",
  AEPS2_BIOMETRICKYC: "aeps/merchantBiomatricKyc",
  AEPS2_OUTLET_LOGIN: "aeps/twoFaFp",
  AEPS2_CASHWITHDRAWAL: "aeps/cashWithdrawlFp",
  AEPS2_AADHAARPAY: "aeps/aadhaarPayFp",
  AEPS2_BALANCE: "aeps/balanceInquiryFp",
  AEPS2_STATEMENT: "aeps/miniStatementFp",
  AEPS2_STATES: "aeps/getStatesFp",
  AEPS2_BANKS: "aeps/getBanksFp",
  REMITTER_KYC: "dmr/remitterKyc",
  REMITTER_KYC_dmt2: "dmr/remitterEkycDmt2",
  DMT2_REGISTER_REM: "dmr/registerRemitterDmt2",
  // DMT2_MT: "dmr/transactionDmrDmt2",
  OTP_PSPRINT: "dmr/otpForDmt2",
  DMR_MONEY_TRANSFER: "dmr/transactionDmr",
  REGISTER_REMITTER_DMT3: "dmr/registerRemitterDmt3",
  DMT3_ADD_REM: "dmr/remitterEkycDmt3",
  GET_REMMITTER_STATUS_DMT3: "dmr/getRemitterStatusDmt3",
  GET_REMMITTER_STATUS_DMT3: "dmr/getRemitterStatusDmt3",
  VALIDATE_SUP_OTP: "dmr/verifySupRemitter",
  VALIDATE_EXP_OTP: "dmr/verifyExpRemitter",
  VALIDATE_SUP_OTP: "dmr/verifySupRemitter",
  OTP_EXP: "dmr/otpExp",
  OTP_dmt1: "dmr/transactionOtpDmt1",
  GET_REMMITTER_STATUS_NEW: "dmr/getRemitterStatusNew",
  GET_REMMITTER_STATUS_SUPER: "dmr/remitterStatusSuper",
  GET_TXN_ID_CR_REQUEST: "user/getTxnIdCrRequest",
  CREATE_AEPS_SCHEME: "schemes/createAepsScheme",
  CREATE_CARD_SCHEME: "schemes/createCardScheme",
  UPDATE_AEPS_SCHEME: "schemes/updateAepsScheme",
  UPDATE_CARD_SCHEME: "schemes/updateCardScheme",
  CREATE_UPI_SCHEME: "schemes/createUpiScheme",
  UPDATE_UPI_SCHEME: "schemes/updateUpiScheme",
  ADMIN_RESEND_TRANSACTION: "admin/resendTransaction",
  GET_AEPS_SCHEMA: "schemes/aepsSchemes",
  GET_CARD_SCHEMA: "schemes/cardSchemes",
  PAN_LINK: "admin/mobileUpdate",
  PAN_VERIFY: "admin/mobileUpdateVerify",
  CREATE_QR: "admin/generateVirQr",
  GET_TIME: "https://timeapi.io/api/time/current/zone?timeZone=Asia%2FKolkata",
  GET_MERCHANTS: "admin/getMerchantsData",
};
export default ApiEndpoints;
